version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.1

jobs:
  setup:
    docker:
      # Use Python convenience image so pip is available, version number is arbitrary
      - cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install YAML and TOML parsers
          command: python3 -m pip install pyyaml tomli
      - run:
          name: Generate config
          command: python3 .circleci/generate_config.py > generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup
